In [1]:
%cd ../

/home/hoanghu/projects/fw-models

In [2]:
from transformers import AutoModel

import numpy as np
import pandas as pd
from tqdm import tqdm

# Load meal names

In [3]:
meal_names = pd.read_excel("data/processed/phase_4/dim_meal_names.xlsx")
meal_names.head()

   meal_id                                      meal
0     9017            "Butter" härkäpapua & pähkinää
1     7201              2023 Härkäpu-sienilasagnette
2     9032           Appelisiini-luomukikhernecurrya
3     9102  Artisokkavugetteja & tuoretomaattisalsaa
4     7010             Aurajuusto-pinaattilasagnette

In [4]:
pcs = pd.read_excel("data/processed/phase_4/dim_pieces_per_dish.xlsx")
pcs.head()

        date restaurant   meal_type  pcs  meal_id
0 2023-01-02        che        fish   78  9500055
1 2023-01-02        che       vegan   84     6128
2 2023-01-02        che        meat  165  9500160
3 2023-01-03        che  vegetarian   29     1270
4 2023-01-03        che        fish  105     6156

In [5]:
meal_ids = pcs['meal_id'].unique()

meal_names = meal_names[meal_names['meal_id'].isin(meal_ids)]

meal_names.shape

(470, 2)

# Encode

In [ ]:
# tqdm.pandas()
# EMBEDDING_MODEL_NAME = "jinaai/jina-embeddings-v3"


# embedding_model = AutoModel.from_pretrained(EMBEDDING_MODEL_NAME, trust_remote_code=True)
# embds = meal_names['meal'].progress_apply(lambda s: embedding_model.encode(s, task="text-matching", truncate_dim=128))

2024-12-02 12:03:38.723668: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-02 12:03:38.746099: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733133818.769959  119239 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733133818.774334  119239 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-02 12:03:38.799198: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [13]:
embds = np.load("data/inter/meal_names.npz.npy")
meal_names['embedding'] = embds.tolist()
meal_names.head()

,meal_id,meal,embedding
4,7010,Aurajuusto-pinaattilasagnette,"[0.01167771965265274, -0.03902484104037285, 0...."
5,7010,Aurajuusto-pinaattilasagnettea,"[0.013460036367177963, -0.047017842531204224, ..."
9,1751,BBQ-broilerikastiketta,"[0.05039491131901741, 0.03726926073431969, 0.0..."
10,1751,BBQ-Broilerikastiketta,"[0.06594163179397583, 0.037054307758808136, 0...."
13,200006,Bar Myöhä Bbq-seitanbowl,"[0.020469341427087784, 0.026279253885149956, 0..."

In [14]:
path = "data/inter/meal_names_embds.parquet"
meal_names.to_parquet(path)