***[May 29]***

This notebook is dedicated for filtering specific meals for each weekday given a restaurant

In [1]:
%cd ../../

/Users/hoangle/Projects/untangling-people/ylva/fwo_models

In [2]:
import polars as pl

# Load models

In [3]:
path = "data/processed/dim_meal_types.xlsx"

dim_meal_types = pl.read_excel(path)
dim_meal_types

shape: (7, 3)
┌──────────────┬────────────┬──────────────┐
│ meal_type_id ┆ meal_type  ┆ meal_type_en │
│ ---          ┆ ---        ┆ ---          │
│ i64          ┆ str        ┆ str          │
╞══════════════╪════════════╪══════════════╡
│ 1            ┆ Kala       ┆ fish         │
│ 2            ┆ Liha       ┆ meat         │
│ 3            ┆ Kana       ┆ chicken      │
│ 4            ┆ Vegaani    ┆ vegan        │
│ 5            ┆ Kasvis     ┆ vegetarian   │
│ 6            ┆ Buffet     ┆ buffet       │
│ 7            ┆ Not Mapped ┆ not_mapped   │
└──────────────┴────────────┴──────────────┘

In [4]:
path = "data/processed/dim_meals.parquet"
dim_meals = (
    pl.read_parquet(path)
    # .drop('meal_codes', 'names', 'src')
)
dim_meals.head()

shape: (5, 9)
┌─────┬────────────┬─────────────┬─────────────┬───┬────────────┬─────────────┬──────┬─────────────┐
│ id  ┆ meal_codes ┆ names       ┆ restaurants ┆ … ┆ schoolyear ┆ attributes  ┆ co2  ┆ src         │
│ --- ┆ ---        ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---         ┆ ---  ┆ ---         │
│ i64 ┆ list[i64]  ┆ list[str]   ┆ list[i64]   ┆   ┆ str        ┆ list[str]   ┆ f32  ┆ list[str]   │
╞═════╪════════════╪═════════════╪═════════════╪═══╪════════════╪═════════════╪══════╪═════════════╡
│ 0   ┆ [90000000] ┆ ["Kikhernet ┆ [1]         ┆ … ┆ 23-24      ┆ []          ┆ 0.41 ┆ ["pos_Jan23 │
│     ┆            ┆ aginea& syy ┆             ┆   ┆            ┆             ┆      ┆ -Oct24"]    │
│     ┆            ┆ somenajo…   ┆             ┆   ┆            ┆             ┆      ┆             │
│ 1   ┆ [90000001] ┆ ["Rapea Mei ┆ [1, 4]      ┆ … ┆ 23-24      ┆ []          ┆ 1.26 ┆ ["pos_Jan23 │
│     ┆            ┆ ramikana"]  ┆             ┆   ┆            ┆             ┆      ┆ -Oct24"]    │
│ 2   ┆ [7203]     ┆ ["Kasvismuh ┆ [1, 2, 4]   ┆ … ┆ 23-24      ┆ []          ┆ 0.42 ┆ ["pos_Jan23 │
│     ┆            ┆ ennos       ┆             ┆   ┆            ┆             ┆      ┆ -Oct24",    │
│     ┆            ┆ Caponata"]  ┆             ┆   ┆            ┆             ┆      ┆ "menus_mea… │
│ 3   ┆ [9058]     ┆ ["TexMex-si ┆ [1, 2, 4]   ┆ … ┆ 24-25      ┆ ["gluten_fr ┆ 0.56 ┆ ["pos_Jan23 │
│     ┆            ┆ emenpyörykö ┆             ┆   ┆            ┆ ee", "vegan ┆      ┆ -Oct24",    │
│     ┆            ┆ itä ja A…   ┆             ┆   ┆            ┆ -kpl"]      ┆      ┆ "menus_mea… │
│ 4   ┆ [6877]     ┆ ["Kasvisjal ┆ [1, 2, 4]   ┆ … ┆ 24-25      ┆ []          ┆ 0.44 ┆ ["pos_Jan23 │
│     ┆            ┆ apenonugget ┆             ┆   ┆            ┆             ┆      ┆ -Oct24",    │
│     ┆            ┆ teja, to…   ┆             ┆   ┆            ┆             ┆      ┆ "menus_mea… │
└─────┴────────────┴─────────────┴─────────────┴───┴────────────┴─────────────┴──────┴─────────────┘

In [5]:
path = "data/processed/pos.xlsx"
pos = pl.read_excel(path)
pos.head()

shape: (5, 6)
┌─────┬────────────┬─────────┬─────────────────────┬─────┬──────────────┐
│ id  ┆ restaurant ┆ meal_id ┆ datetime            ┆ pcs ┆ src          │
│ --- ┆ ---        ┆ ---     ┆ ---                 ┆ --- ┆ ---          │
│ i64 ┆ i64        ┆ i64     ┆ datetime[ms]        ┆ i64 ┆ str          │
╞═════╪════════════╪═════════╪═════════════════════╪═════╪══════════════╡
│ 0   ┆ 1          ┆ 55      ┆ 2023-01-02 10:31:00 ┆ 1   ┆ Sold lunches │
│ 1   ┆ 1          ┆ 8       ┆ 2023-01-02 10:32:00 ┆ 1   ┆ Sold lunches │
│ 2   ┆ 1          ┆ 55      ┆ 2023-01-02 10:32:00 ┆ 1   ┆ Sold lunches │
│ 3   ┆ 1          ┆ 8       ┆ 2023-01-02 10:35:00 ┆ 1   ┆ Sold lunches │
│ 4   ┆ 1          ┆ 55      ┆ 2023-01-02 10:36:00 ┆ 2   ┆ Sold lunches │
└─────┴────────────┴─────────┴─────────────────────┴─────┴──────────────┘

# Filter

In [6]:
schoolyear = '24-25'
special = "today's special"
restaurant = 1
weekday = 1

In [7]:
(
    dim_meals
    .filter(
        (1 == 1)
        & (pl.col('restaurants').list.contains(restaurant))
        & (pl.col('schoolyear') == pl.lit(schoolyear))
        # & (~pl.col('attributes').list.contains(pl.lit(special)))
        & (pl.col('meal_type').is_in([1]))
        # & ((pl.col('meal_type') == 4) | (pl.col('meal_type') == 5))
    )
    .select('id')
    .to_numpy().squeeze()
)

array([  5,   8,  19,  20,  23,  27,  41,  51,  57,  59,  62,  70,  73,
        75,  93,  95, 108, 110, 116, 118, 124, 132, 134, 147, 149, 152,
       162, 185, 191, 192, 193, 198, 217, 221, 222, 233, 237, 281, 288,
       299, 305, 308, 312, 314, 328, 339, 362, 363, 375, 433, 460, 471,
       472, 492, 528])